local P=cloneref(game:GetService("Players"))local R=cloneref(game:GetService("RunService"))local W=cloneref(game:GetService("Workspace"))local function cTL(t)if t:FindFirstChild("ToolNameLabel")then return end local b=Instance.new("BillboardGui")b.Name="ToolNameLabel"b.Adornee=t b.Size=UDim2.new(0,100,0,30)b.StudsOffset=Vector3.new(0,2,0)b.AlwaysOnTop=true b.MaxDistance=math.huge local l=Instance.new("TextLabel")l.Size=UDim2.new(1,0,1,0)l.BackgroundTransparency=1 l.Text=t.Name l.TextColor3=Color3.new(1,1,1)l.TextScaled=true l.Font=Enum.Font.SourceSansBold l.Parent=b b.Parent=t end
local function aO(t)if not t:FindFirstChildOfClass("Highlight")then local h=Instance.new("Highlight")h.FillColor=Color3.new(1,1,0)h.OutlineColor=Color3.new(1,0,0)h.Parent=t end cTL(t)end
for _,o in W:GetDescendants()do if o:IsA("Tool")and not(o.Name=="RedFlag"or o.Name=="BlueFlag"or o.Name=="Item")then aO(o)end end
W.DescendantAdded:Connect(function(o)if o:IsA("Tool")then aO(o)end end)
local function cESP(m,o,f)if m and not m:FindFirstChildOfClass("Highlight")then local h=Instance.new("Highlight")h.Parent=m h.Adornee=m h.FillTransparency=0.75 h.FillColor=f h.OutlineColor=o h.OutlineTransparency=0 end end
local function cHI(c,t)local h=c:FindFirstChild("Head")if h and not h:FindFirstChild("HealthGui")then local g=Instance.new("BillboardGui")g.Name="HealthGui"g.Size=UDim2.new(0,100,0,30)g.AlwaysOnTop=true g.MaxDistance=math.huge g.Parent=h local l=Instance.new("TextLabel")l.Size=UDim2.new(1,0,1,0)l.BackgroundTransparency=1 l.TextScaled=true l.Text=""l.TextColor3=t l.Font=Enum.Font.SourceSansBold l.Parent=g end end
local function uHI()for _,p in P:GetPlayers()do local c=p.Character if c then local h=c:FindFirstChildOfClass("Humanoid")local hd=c:FindFirstChild("Head")if h and hd then local tc=h.MaxHealth>500 and Color3.new(1,0,0)or Color3.new(1,1,1)cHI(c,tc)local g=hd:FindFirstChild("HealthGui")if g then local l=g:FindFirstChildOfClass("TextLabel")if l then l.Text=math.floor(h.Health).."/"..h.MaxHealth l.TextColor3=tc end end end end end end
local function cG(g,o,f)if g then for _,o in g:GetChildren()do local h=o:FindFirstChildOfClass("Humanoid")local r=o:FindFirstChild("HumanoidRootPart")if h and r then cESP(o,o,f)end end end end
local function hG()for _,o in workspace:GetDescendants()do if o:IsA("Model")and o.Name=="Generator"then cESP(o,Color3.new(1,1,0),Color3.new(1,1,0.5))end end end
local function uESP()while true do local ps=P:GetPlayers()for _,p in ps do local c=p.Character if c then for _,o in c:GetChildren()do if o:IsA("Highlight")then o:Destroy()end end local h=c:FindFirstChildOfClass("Humanoid")if h then if h.MaxHealth>500 then cESP(c,Color3.new(1,0,0),Color3.new(1,0.5,0.5))cHI(c,Color3.new(1,0,0))else cESP(c,Color3.new(0.5,0.5,0.5),Color3.new(0.7,0.7,0.7))cHI(c,Color3.new(1,1,1))end end end end uHI()hG()task.wait(3)end end
task.spawn(uESP)
